# Twitter API v2 配置
twitter:
  api:
    bearer-token: AAAAAAAAAAAAAAAAAAAAAPqP8gEAAAAA9kijiLWK2xqUVSFZibEFfna2gGs%3DWilvmCsBgPNAnVtDGB1Oi1scjnvIu7W3AcNYqzdn6NJVVrajC2
    base-url: https://api.x.com/2
    timeout: 30000
    # 代理配置
    proxy-enabled: true
    proxy-host: localhost
    proxy-port: 7899
